[package]
name = "image-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# opencv = "0.86.1" # causes problems on arm Mac :(
image = "0.24.7"
